name = "ownnews-processor"
main = "src/index.ts"
compatibility_date = "2024-04-01"

[ai]
binding = "AI"

[triggers]
crons = [
    # JST 06:00-08:00 -> UTC 21:00-23:00 (Runs every 10 mins)
    "*/10 21,22 * * *",
    # JST 11:00-13:00 -> UTC 02:00-04:00
    "*/10 2,3 * * *",
    # JST 16:00-18:00 -> UTC 07:00-09:00
    "*/10 7,8 * * *",
    # JST 18:00-20:00 -> UTC 09:00-11:00
    "*/10 9,10 * * *",
    # JST 21:00-23:00 -> UTC 12:00-14:00
    "*/10 12,13 * * *"
]
